### ISSUE TITLE
Check alkalinity and change if needed

### ISSUE THREAD

**Issue by tmills-usgs** [tmills-usgs/Dinero_Project#21]

**Comment by kwaltond** [comment]
KWD completed checking on 4/1/2015.  Returned Files to Joe for uploading changed values.

**Comment by tmills-usgs** [comment]
Alkalinity issues noted in 2013_2014_QAQC\Alksummary\Alkcheck.xls

**Comment by tmills-usgs** [comment]
Changed in NWIS
