### ISSUE TITLE
Summarize QA/QC results of 2013 and 2014 samples 

### ISSUE THREAD

**Issue by kwaltond** [tmills-usgs/Dinero_Project#25]
Data for field and Lab replicates, SRS samples, and Blanks (and charge balance)  need to be summarized in tables and then written up. This will form the basis for the QA/QC section of the new report, but will also aid in getting reruns/assistance from Ruth Worf.   

Assigned to Joe, but KWD will assist interpretation and preparation of summary.

**Comment by kwaltond** [comment]
Because there seem to be different issues in different years, please keep the 2013 and 2014 data separated on different tables. It might be interesting to show her how the years compare to each other.

**Comment by tmills-usgs** [comment]
Summaries almost complete except for SRS summaries. SRS samples have multiple results.
