### ISSUE TITLE
Make timeseries plots

### ISSUE THREAD

**Issue by tmills-usgs** [tmills-usgs/Dinero_Project#5]
Make time series plots for sites listed in milestone for WEBEX.

**Comment by tmills-usgs** [comment]
Done and emailed to KWD for review

**Comment by kwaltond** [comment]
I do not have time series plots??   Just the Nelson/sugarloaf you sent this
morning


On Tue, Mar 31, 2015 at 2:57 PM, T. Joe Mills <notifications@github.com>
wrote:

> Done and emailed to KWD for review
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tmills-usgs/Dinero_Project/issues/5#issuecomment-88242340>
> .
>



-- 
Katie Walton-Day
U.S. Geological Survey
Denver Federal Center
Box 25046, MS 415
Denver, CO 80225

Phone:  303.236.6930
Fax:  303.236.4912
email:  kwaltond@usgs.gov

**Comment by tmills-usgs** [comment]
Emailing once github sync complete

**Comment by tmills-usgs** [comment]
KWD approved
